const {readFileSync}=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const html=readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8');
const script=html.match(/<script>\s*([\s\S]*?)<\/script>/)[1];
new vm.Script(script);
let open=false,visible=true;const panel={scrollTop:0},listeners={};
const target={closest:s=>s==='#outro'?{}:null};
const context=vm.createContext({Math,document:{getElementById:id=>id==='outro-inner'?panel:{classList:{contains:()=>id==='side-panel'?open:visible}}},window:{addEventListener:(name,fn)=>listeners[name]=fn}});
vm.runInContext('let targetScroll=1700,scrollY=1700;const MAX_SCROLL=1700;'+script.slice(script.indexOf('function panelOwnsInput'),script.indexOf('function portfolioNavigate')),context);
const route=(delta,touch=false)=>{context.target=target;return vm.runInContext(`routeScroll(target,${delta},${touch})`,context)};
const position=()=>vm.runInContext('targetScroll',context);
assert.equal(route(-100),true);assert.equal(position(),1620,'Wheel exits About at top');
panel.scrollTop=300;assert.equal(route(-100),false);assert.equal(position(),1620,'Wheel inside text stays native');
assert.equal(route(100),false,'Downward wheel stays in About');
route(-100,true);assert.equal(panel.scrollTop,200);assert.equal(position(),1620,'Touch scrolls text before tower');
panel.scrollTop=20;route(-50,true);assert.equal(panel.scrollTop,0);assert.equal(position(),1560,'Only leftover gesture distance moves tower');
open=true;route(-100,true);assert.equal(position(),1560,'Details block scene');open=false;
visible=false;route(-100,true);assert.equal(position(),1360,'Same gesture continues into tower');
route(-10000,true);assert.equal(position(),0,'Can return all the way to intro');
console.log('PASS: syntax, wheel handoff, native text scrolling, touch handoff, gesture remainder, details isolation and return to intro');
